services:
  audit-service:
    build: .
    # container_name: audit_service
    env_file:
      - .env
    environment:
      AUDIT_DB_DSN: ${AUDIT_DB_DSN}
      AUDIT_TOKEN: ${AUDIT_TOKEN}
    ports:
      - "8002:8002"
    networks:
      - shared_net

networks:
  shared_net:
    external: true